#!/bin/sh
#
# Automatically adds branch name and time spent to every commit message.
#

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  SOURCE_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$SOURCE_DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SOURCE_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

runGitCommitMsg() {
	java -cp "$SOURCE_DIR" GitCommitMsg "$BRANCH" "$MESSAGE"
}

# Get the branch name
BRANCH=$(git branch | grep '*' | sed 's/* //')

# Get the whole commit message
MESSAGE=$(cat "$1" | sed '/^#.*/d')

if [ ! which java >/dev/null 2>&1 ]; then
  echo "Java is not installed. Please install Java"
  exit 1 
fi

if [ -e GitCommitMsg.class ];then
	runGitCommitMsg
else
	javac "$SOURCE_DIR"/GitCommitMsg.java
	runGitCommitMsg 
fi

exit 0